### ISSUE TITLE
Arbitrary code execution on extension response

### ISSUE THREAD

**Issue by Jaakkonen** [Ulauncher/Ulauncher#1032]
### Environment

Linux, Sway, commit e004a49

### Bug description

Ulauncher v6 uses pickle encoded packets over UNIX socket `/run/user/$UID/ulauncher_control`. This exposes Ulauncher to the typical pickle security issues as it can proxy entire objects with their code associated with them.

This allows a malicious extension to execute code in the Ulauncher parent process. As a proof of concept one can change `ulauncher.api.Client` to send a class containing malicious code in `__str__`. That will be called just after the `pickle.loads` loads the response at
https://github.com/Ulauncher/Ulauncher/blob/e004a49daf4f24d99ab827f449e1519b36577a93/ulauncher/utils/framer.py#L124

PoC:
Add
```python
class A:
    def __str__(self):
        import os
        os.execv("/bin/bash", ("bash",))
```
to `Client.py` and change `Client.send` method to send packet `self.framer.send(A())`.

Either it should be clearly stated that this socket allows arbitrary code execution in the parent process or the communication changed to some protocol not allowing for such issues (JSON/BSON/protobuf) and using a secure parser for that.

The socket seems to be writable by only the owner so this doesn't give ability for cross-user escalation but enables an attacker to pivot their software to run in other processes which may have less monitoring and less strict security policy (for example selinux/apparmor not permitting running arbitrary applications but allowing socket writes to /run/user/ while ulauncher is most often permitted to run anything as it's what it is meant to do).

### Log output

```shell
(ulauncher:442134): Gtk-CRITICAL **: 18:57:05.568: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[user@computer Ulauncher]$
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by Jaakkonen** [comment]
This essentially allows process-to-process pivoting, not privilege escalation, and gives a arbitrary socket write to arbitrary code execution primitive. In SELinux/AppArmor context one may have extensions set up to not allow for executing arbitrary binaries but this gives an ability to bypass that via executing code in the main ulauncher process.

These aren't that bad security issues so I suggest accepting these risks and documenting that in the docs for extensions.

**Comment by friday** [comment]
I see. I would agree that's a reasonable solution, but only if we can target users who are concerned with security without scaring users who are not. If you call attention to it in the wrong way users might not understand but still be discouraged from using Ulauncher, thinking it's a more serious security issue instead they use something equally or even less secure.

If you have a suggestion (PR or just an answer) I'd be open to considering it, but I would want to discuss it with the other maintainers. For example I would want us to be "disclosing a process-to-process pivoting vulnerability", because at least 90% of our users wouldn't even know what that is I'm sure. But adding a clarification/disclosure somewhere that Ulauncher extensions run in unrestricted user scopes would probably be a better formulation.

My knowledge of SELinux/AppArmor is limited, and I though that the way extensions are executed there would be no way for Ulauncher users to restrict extensions runtime privileges. We could do more work to improving this aspect. For example the extensions could run as a separate user without write or even read access to the user home dir, but many extensions rely on being able to for example search the home dir for files, and would break unless they were able to at least ask for this permission. gornostal already had these concerns many years ago and wanted to improve extension security. We talked then about using something like seccomp-bpf/firejail and syscall whitelisting (extensions having to declare privileges in the manifest) that the user could choose to approve or not. It was my suggestion, but really out of my area of expertise. I'm sure you know a lot more than either of us on this, and if you have more ideas/input we definitely welcome any help we can get.

I'm sure you're caught up with that we are aware and open about there being room for improvement in our extension implementation (see #966, #920, #1020, https://github.com/Ulauncher/Ulauncher/issues/306#issuecomment-902837341), but it's a major breaking change that would require a lot of time.

**Comment by Jaakkonen** [comment]
Yep. I agree with the problem about documenting this. It gets really technical when thinking if some issue is really serious or if it should only be considered under specific conditions. For now I think just having this in viewable from the github issue history is enough to be honest.

In the long term an extension sandbox would definitely be the way to go. [Podman](https://github.com/containers/podman) is a really good example of implementing docker-style container sandboxing in unprivileged environment. That may be helpful when getting around implementing that (if somebody has the time and interest to also do that :D).

**Comment by friday** [comment]
I never thought of using something like Podman for it. I have considered a different solution: https://wasi.dev/ https://youtu.be/ggtEJC0Jv8A.

Both have their pros and cons, but ultimately I wouldn't know how to integrate either of them because they are too secure and extensions inherently need to be able to do things that are not secure, like managing other applications runtime on the host system, start daemons, kill processes, play/pause/stop music, skip to the next song, integrate with users clipboard managers etc and neither WASI or Docker/Podman were built to allow that sort of flexibility, while Firejail was.
