### ISSUE TITLE
Blurry UI in Wayland

### ISSUE THREAD

**Issue by runkaiz** [Ulauncher/Ulauncher#1033]
### Environment

Pop!_OS / Arch Gnome 42 Wayland

### Bug description

When fractional scaling is on, Ulauncher appears to have very blurry UIs similar to what one would expect on an Electron application running in xwayland. Is Ulauncher not wayland native yet?

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
https://github.com/Ulauncher/Ulauncher/discussions/991#user-content-wayland

**Comment by runkaiz** [comment]
I just have a question, will this ever get fixed or is slapping it on "it's an issue and no viable workaround" for the rest of its time. Is there any intention on making it native Wayland in the future?

**Comment by friday** [comment]
If you really want to use Wayland read the link. It will break important Ulauncher functionality though.

Wayland is the death of apps like Ulauncher. We need to do things that was possible and supported before, but they pulled the carpet from underneath because Wayland decided it wasn't their job to implement it. GTK decided it wasn't their job either and there's no way for apps to send em hints any more. It's the same with any launcher out there possibly except pop-launcher, because that runs as a shell extension and integrate directly with Gnomes APIs, not GTK.

**Comment by runkaiz** [comment]
Thanks for the clarification, in my use case forcing ulauncher to work in Wayland doesn't affect any of the capabilities I wanted so I am pretty luck haha. This truly is a headache in general because the two protocol differs so much. I am usually fine with xwayland but now with hidpi screens xwayland just blurs everything with any sort of scaling. Anyways, thank you for your efforts!

**Comment by friday** [comment]
It will break centering though. The Gnome method to center app windows by default centers them both vertically and horizontally, which is problematic because the window height is dynamic depending on your query.
