### ISSUE TITLE
[v6] ExtensionCustomAction 'dumps' the data with pickle, but not 'loads' the data when use

### ISSUE THREAD

**Issue by sunn4room** [Ulauncher/Ulauncher#1099]
### Environment

archlinux, bspwm

### Bug description

ExtensionCustomAction 'dumps' the data with pickle, but not 'loads' the data when use.

I write a simple extension, and I get a binary data in 'on_item_enter(self, data)' function. So I think it's probably a bug.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Other extensions work with ExtensionCustomAction though. Could you post a link to the extension?

**Comment by friday** [comment]
I just noticed you're actually using the new v3 API for extensions. It could be that the bug is only happening for `on_item_enter` (I have mostly been testing with very basic extensions).

You should be aware that the v3 extension API hasn't been finalized. I appreciate that you're already testing it though. We try to not break compatibility with existing v2 extensions, but v3 has no release yet, and we want to be able to make incompatible changes (like #1097 for example).

**Comment by sunn4room** [comment]
I just read the source code of v6(api v3), and noticed this problem. So I tested it with the example extension in doc/extension/tutorial.rst, and the bug occured, I got binary str with the data param.

this is a small bug. Just load the data in somewhere

**Comment by friday** [comment]
Thanks :+1: 

I have been focused on getting the simple things right first, and never even tested `ExtensionCustomAction`, although I have implement the event listener method and the documentation as part of other changes. I am also considering further changes to this API, like not to serialize and send the data at all. The Ulauncher app can't do anything with it. All you need to do it send a [reference](https://docs.python.org/3/library/functions.html#id) to the data and then receive the reference. The reference has to be serialized/deserialized of course, but this should be more performant for users otherwise sending complex data.

**Comment by sunn4room** [comment]
I like the v3 api, and it makes the custom extensions easy to write. A useful extension object just do three thing:

- handle life cycle
- handle query change, return result list
- handle item enter, return new list if necessary

it's great that all in one class, and I don't have to write another class about event or listener.

good job. and i hope toget the v3 api as soon as possible!  XD

**Comment by friday** [comment]
I'll reopen this as a reminder until it's fixed :)

**Comment by friday** [comment]
Fixed. Thanks again for reporting :+1: It now only sends the reference to the data also, which solves one of the issues causing us to need pickle instead of json for the extension communication.
