### ISSUE TITLE
Use git instead of relying on GitHub/GitLab API for extension management

### ISSUE THREAD

**Issue by FinnHering** [Ulauncher/Ulauncher#1162]
### Description

The GitHub API has quite a strict rate limit which could cause installing/updating of plugins to stop working for some time, which is not really user-friendly. 

The `upgrade` or `restore` function of the new CLI for managing Ulauncher extensions (see #1150) is especially affected by this, because it could possibly fire many API requests at once, causing the IP used to be rate limited. 

If we used plain git or a wrapper library for git, we would no longer be affected by rate limiting and also git server agnostic. 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
I just pushed a PR draft that fixes this in a better way (imo). Could you test that it works for you? I think it should mostly work as is, but I need to fix the tests and restore/remove/replace some error handling which I just deleted now as it was in the way.

It's suppose to check for references first, and if you have a tag or branch name starting with `apiv`, ex `apiv3` or `apiv3.1` that matches the current version it will use the highest matching version. Otherwise it will fall back on the default branch.

Because v6 isn't released yet and the new version resolution is undocumented I'm pretty sure the only extensions using these tags/branch names are my own. Ex:
https://github.com/friday/ulauncher-gnome-settings
https://github.com/friday/ulauncher-clipboard
