### ISSUE TITLE
Option to hide all lsp plugins

### ISSUE THREAD

**Issue by ryu0q** [Ulauncher/Ulauncher#1167]
### Description

Something to hide `/usr/share/applications/in.lsp_plug.lsp_plugins*`.
When I try to add it in blacklisted app directories, it just crashes.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
I think this issue is already fixed in Ulauncher v6, so no blacklisting should be needed. If you test v6 (there are no v6 builds yet) and find it to still be an issue, please create another issue.

See https://github.com/Ulauncher/Ulauncher/tree/v6#readme, https://github.com/Ulauncher/Ulauncher/issues/869,  https://github.com/Ulauncher/Ulauncher/issues/833 and https://github.com/Ulauncher/Ulauncher/issues/834
