### ISSUE TITLE
Ulauncher not clearing previous entry

### ISSUE THREAD

**Issue by viggy96** [Ulauncher/Ulauncher#138]
**Steps to reproduce:**
Search for an item
Exit Ulauncher, or open the selected item to make Ulauncher close
Trigger Ulauncher again, and the previous entry is still there

**Ulauncher version**: 3.0.2.r0-0ubuntu1ppa~xenial
**Linux distro**: Ubuntu 16.04.2 LTS
**Desktop environment**: Cinnamon 3.4.1

**Comment by gornostal** [comment]
It's a bug if previous entry is not cleared when you open a selected item.
In that case you provide more details on how to reproduce? I wasn't able to.

If you just switch focus off from Ulauncher and then activate the app again, previous entry should be there. It's by design. There is a ticket to change that behavior #123

**Comment by gornostal** [comment]
I wasn't able to reproduce this
