### ISSUE TITLE
Option to always maintain focus

### ISSUE THREAD

**Issue by bertvandepoel** [Ulauncher/Ulauncher#1405]
### Description

I switched from Gnome Do and Synapse (both are no longer maintained) to Ulauncher. In general I really like it but some behavior is a little confusing to me. One of the things I tend to do often is launch a few applications that I will be using together. The problem is that even with the "Don't hide after losing mouse focus" enabled, Ulauncher will let other applications, including ones it has just launched, steal its focus. This results in me launching one application, then wanting to launch another but Ulauncher losing focus almost immediately once I start typing. An option to maintain focus at all times would be great. In Gnome-do for example I have to press escape or click away for it to disappear.

Ideally I'd have made a PR to have this land quickly, but I have no idea how to fix this. I did notice #1128 but I'm not sure if the fix for that could also as a side-effect fix this or not.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by bertvandepoel** [comment]
I think you've maybe misunderstood what I meant to say. I mean I launch application A and then retap the shortcut to launch Ulauncher but while I'm typing the name of application B, application A spawns its window and therefore depending on my settings either Ulauncher disappear or loses focus. So it's not that I want to keep Ulauncher there and clear it after launching, but rather I want it to not disappear or lose focus if a window spawns while I'm using Ulauncher.

**Comment by friday** [comment]
Oh, then I did indeed misunderstand. That sounds like a legit thing to fix. That should probably be covered by "Don't hide after losing mouse focus" :+1:

**Comment by friday** [comment]
Testing this on my DE I can reproduce the issue, but I don't seem to be able to fix it `grab_focus()` didn't work.

**Comment by bertvandepoel** [comment]
In the past I was running Ubuntu 18.04 with GNOME Do and it was able to do it, but I couldn't tell you how. Sadly desktop development isn't really something I've got any experience with. But I'm glad you see what I mean. And yeah, GNOME's an experience :P

**Comment by friday** [comment]
I did some looking into this and:
1. The feature was not intended to do this after all: #640
2. It's not possible to control the focus from an app any more because of Wayland. Only the DE/compositor/window manager can do that.

We can keep Ulauncher open when it loses focus (there's an undocumented experimental feature in v6 for this: https://github.com/Ulauncher/Ulauncher/commit/ec58eadcb07dad65ae7049d57768103188156e0f but  you have to change ~/.config/ulauncher/settings.json yourself because there's no UI for it).

However, we can't prevent the app you launch from stealing the focus from Ulauncher. This is normally what you want it to do. We also can't give Ulauncher the focus back afterwards.

To the degree that this would work it would only work in X11, it would require a dependency and would introduce race conditions (we know this because we removed similar hacks from from Ulauncher because they were problematic), and this use case is definitely not important enough for this.
