### ISSUE TITLE
clean up script that will migrate the user's v5 installation to v6

### ISSUE THREAD

**Issue by iaacornus** [Ulauncher/Ulauncher#1428]
### Description

v6 will introduce quite a lot of changes, especially in extensions part and in the use of systemd instead of xdg-autostart, to mention some. So installation of v6 will leave some parts of v5 dangling out there. I think it would be nice to have an install script that will clean up those files and will automatically migrate the extensions to comply to changes in v6. I can work on this one

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing feature requests](https://github.com/Ulauncher/Ulauncher/labels/feature) before suggesting this.

### Feature isn't possible to support as an extension.

- [X] This feature request cannot satisfactory be supported as a third party extension.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment]
It already exists:

You can import and run this if you want, but I don't want this to run for everyone until v6 is stable released. If people upgrade and downgrade immediately because v6 doesn't work optimally for them, we want to keep their old files.

https://github.com/Ulauncher/Ulauncher/blob/v6/ulauncher/utils/migrate.py#L141C5-L141C25

**Comment by iaacornus** [comment]
well, that's understandable, thank you.
