### ISSUE TITLE
Non-standard cache path

### ISSUE THREAD

**Issue by hickscorp** [Ulauncher/Ulauncher#152]
In my `~/.cache` directory, two folders are being created by ULauncher, one not following the standard convention:

- `~/.cache/ulauncher` which is correct, and probably created by the Webkit internal based on the app id.
- `~/.cache/ulauncher_cache` which has that redundant `_cache` suffix.

It would be nice to fix that to have a more standard cache directory structure.

The responsible line is in the [confg constants](https://github.com/Ulauncher/Ulauncher/blob/86939732c978a97a4941bdd2d3f6848277b1e275/ulauncher/config.py#L20) but changing that would be a mistake: a migration would have to be written to properly move existing cache files and then destroy the old `ulauncher_cache` folder *if empty*.

**Comment by gornostal** [comment]
There is a bug in WebKit2 that removes cache folder if it has the same name as the executable. Hence `~/.cache/ulauncher_cache`.
It's actually mentioned in that file you linked

**Comment by branb** [comment]
I'm not sure if ```~/.cache``` is the proper base directory for *everything* that is currently inside of it. As stated in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> ```$XDG_CACHE_HOME``` defines the base directory relative to which user specific **non-essential data files** should be stored. If ```$XDG_CACHE_HOME``` is either not set or empty, a default equal to ```$HOME/.cache``` should be used.

At the moment, extensions and themes are saved there as well, and I'm not too sure what's inside of the ```.db``` files. Ulauncher and all it's extensions should be able to work as expected when you delete the cache folder at any point of time during it's runtime. The first sentence from the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#varcacheApplicationCacheData) explains it best:

> ```/var/cache``` is intended for cached data from applications. Such data is locally generated as a result of time-consuming I/O or calculation. The application must be able to regenerate or restore the data. Unlike ```/var/spool```, the cached files can be deleted without data loss. The data must remain valid between invocations of the application and rebooting the system.

I think at least the extensions, themes and maybe some - if not all - of the ```.db``` files should be stored into ```~/.local/share/ulauncher/``` instead. This way the WebKit-Bug would be completely irrelevant as well, because even though it may be annoying, anything stored in ```~/.cache``` should not cause any issues when deleted no matter if by bug, intentionally or whatever.

The way I stumbled across this issue here is because I was looking into ```~/.local/share/``` and surprised that there was no ulauncher directory.

**Comment by friday** [comment]
> At the moment, extensions and themes are saved there as well, and I'm not too sure what's inside of the `.db` files. Ulauncher and all it's extensions should be able to work as expected when you delete the cache folder at any point of time during it's runtime. The first sentence from the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#varcacheApplicationCacheData) explains it best:

All of that is regenerated, though I guess it assumes you are online, and at least one of the .db-files contains your usage pattern, so *some* data is lost.

> The way I stumbled across this issue here is because I was looking into `~/.local/share/` and surprised that there was no ulauncher directory.

`~/.config/ulauncher/` contains your settings, shortcuts, list of extensions and their settings.

**Comment by gornostal** [comment]
> .db-files contains your usage pattern, so _some_ data is lost.

Now I think that it's better to store .db files and themes in `~/.local/share`, because it's where per-user data should go.
As for the extensions, @friday is right -- they are regenerated. Ulauncher will download them if you have some extensions listed in `~/.config/ulauncher/extensions.json` but `~/.cache/ulauncher_cache/extensions` is empty. So having them in `~/.cache` makes sense for me.

**Comment by gornostal** [comment]
I've created a separate task for that improvement: #347
