### ISSUE TITLE
Cache the apps (Initially at boot applications do not show up in the menu)

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#154]
Cache the apps so the user won't have to wait until the apps are indexed on Ulauncher restart

**Comment by gornostal** [comment]
Done in v4.0.9

**Comment by cmprmsd** [comment]
Hey! Is this feature broken due to regression bugs?
My launcher opens quickly, but after typing the first letter of an application name, the app freezes for some time. Only for the first search after boot, so I guess the caching/indexing is not happening at startup any more.
Is there a flag that I can enforce for startup to create the cache immediately?

Thanks in advance!

**Comment by friday** [comment]
@cmprmsd we're not going to make any more performance improvements for v5. I'm trying to find time to finish the v6 milestone and can't afford distractions.

**Comment by cmprmsd** [comment]
Fine for me! Using the latest git built for the meanwhile. Thanks :)
