### ISSUE TITLE
Option to send usage statistics

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#160]

**Comment by troycurtisjr** [comment]
I also think that many users would be very hesitant to this idea, not to mention it would put the project in the position of potentially having to deal with things like the GDPR and [CCPA](https://oag.ca.gov/privacy/ccpa). I know the Fedora project would really LOVE some decent usage stats, but they very deliberately will not do so because of the burden.

With these things in mind, I vote we close this as "won't do". Thoughts @friday / @gornostal ?

**Comment by friday** [comment]
Yeah. We talked about this on the video call. I think it's best to avoid it all together, even if it's optional. Some very vocal parts of the community really doesn't like telemetry. Even if it's opt-in. For me I get a good picture of the market share and response via https://www.slant.co/topics/3945/~best-linux-app-launchers

These two comes to mind:
* https://github.com/audacity/audacity/discussions/1225 (a company bought and killed Audacity by adding telemetry)
* https://github.com/VSCodium/vscodium

**Comment by gornostal** [comment]
I agree with both of you!
Closing.
