### ISSUE TITLE
Posibility to add settings fields for custom extensions

### ISSUE THREAD

**Issue by nortmas** [Ulauncher/Ulauncher#171]
I'm creating an extension for  [cacher](https://www.cacher.io/) And I need to add settings fields like API Key and Token to connect extension to user account in cacher. But there is no way do it.

**Comment by gornostal** [comment]
Custom extension settings would be a useful feature indeed. I'll add it with the next release.

**Comment by nortmas** [comment]
Perfect! thx!

**Comment by gornostal** [comment]
Hi,
I was wondering, can't you store API Key in a field of type "input"?

**Comment by nortmas** [comment]
Hey, yes, why not, I don't see any obstructions.

**Comment by gornostal** [comment]
> Custom extension settings would be a useful feature indeed. I'll add it with the next release.

It's funny, although I wrote that, now I'm not sure what exactly is missing in Ulauncher Ext. API to have custom settings fields.
You can already have an input or text field.

Could you clarify what you mean by "Possibility to add settings fields"?

**Comment by gornostal** [comment]
please reopen if needed

**Comment by branb** [comment]
Is it possible for an extension to dynamically extend / change the settings during runtime, without restarting Ulauncher? By that I mean not only change values but e.g. add / remove fields as well.

**Comment by gornostal** [comment]
Hi @branb 
Sorry, but no, It's not possible.

There are two reasons to keep the things the way they are: 
1. Only users should be allowed to change the settings
2. If Ulauncher provided an ability (API) to dynamically add/remove keywords, some extensions may abuse that feature, which can cause user frustration.

**Comment by friday** [comment]
Do you mean keywords only? Maybe the underlying need can be solved differently? How about the ability to disable a keyword at runtime only (but not changing the keyword or value). I think I proposed that somewhere. That way the extension could add a hardcoded set of keyword but if some of them can't be supported because for example the binaries are missing, then they can be disabled.

There are a couple of related issues (#306 #276), so it's probably better to continue the conversation there (unless I misunderstood).

**Comment by branb** [comment]
Hey @gornostal 

Thx for the reply. I think I haven't described clearly enough what I meant. I was thinking about the same functionality that you already provide for the *Blacklisted App Dirs*, where the user can add / remove inputs at will. 

>     1. Only users should be allowed to change the settings

The user would still be in full control and the extension wouldn't be able to change the values.

>     2. If Ulauncher provided an ability (API) to dynamically add/remove keywords, some extensions may abuse that feature, which can cause user frustration.

Just out of curiosity: Why is that?

Since an extension can already have multiple keywords and the keywords can be changed dynamically by the user, I don't see why this would bring another problem onto the field.

@friday 

Howdy mate :hand:

I've read the referenced issues and together with your proposal - to make them dynamically enabled / disabled at run time, it seems like we have a plethora of small, seperate issues which are related to either settings or keyword handling.

I certainly like the ideas discussed in those related issues and believe that they would add great value to the application, but I think that the discussed behaviour here is still somewhat different from them, even to dynamically enabling / disabling settings at runtime, which would be sweet too in addition to the discussed issues.

It was interesting to get a closer insight into event loop handling, keyword matching and when an extension gets to output it's stuff to the results list.

**Comment by friday** [comment]
> I certainly like the ideas discussed in those related issues and believe that they would add great value to the application, but I think that the discussed behavior here is still somewhat different from them

Maybe you could create a new issue in that case? Commenting on old closed issues ("necro bumping") and/or posting comments that doesn't contribute to the _original_ discussion (being off topic or "threadjacking") is not against any rules, but it's generally frowned upon and discouraged by github users. Everyone who commented or subscribed to the thread will get an email, and when you want to search for or reference something it should have its own unique id or things will get even more confusing.
