### ISSUE TITLE
Launch at login 'disabled' in Linux Mint 18.3 XFCE

### ISSUE THREAD

**Issue by ayanb1991** [Ulauncher/Ulauncher#210]
**Steps to reproduce:**
Open Preference Dialog -> Launch at login 'disabled'.

**Ulauncher version**: v4.0.6.r1
**Linux distro**: Linux Mint 18.3 Sylvia 64 Bit
**Desktop environment**: XFCE

**Working fine on KDE (Linux Mint 18.3)**

**Comment by gornostal** [comment]
I think I know why this is happening. Please try closing Preferences and opening them again. It should be enabled.

**Comment by Zerocchi** [comment]
Not OP, but I'm running the similar version of Ulauncher and similar DE (XFCE), just different distro which is Xubuntu. I tried closing Preference and opening it again, but the option is still disabled. Tried running with `sudo`, and the option is finally enabled. The problem when running with `sudo` is I will getting an error like this when I'm trying to open Ulauncher without `sudo`

`OSError: [Errno 13] Permission denied: '/home/user/.cache/ulauncher_cache/themes/ubuntu/theme-gtk-3.20.css'`

which probably after-effects of running `sudo ulauncher`, the cache directory become root-owned. I need to delete the entire `~/.cache/ulauncher_cache` for Ulauncher to work again.

**Comment by derkomai** [comment]
Same issue here under elementary OS Loki.

**Comment by gornostal** [comment]
You are seeing a disabled checkbox because you've probably just started Ulauncher application and now it's trying to find itself among installed apps so it can then add itself to the autostart.

I know, this is not the best UX but I just wanted to give you some insight on why you may not be able to tick that checkbox. 
If you close Preferences window and open it 10-60 seconds later, you should be able to enable autostart.

**Comment by gornostal** [comment]
This should be fixed with Ulauncher 4.1.0. I've added app caching there.

**Comment by gornostal** [comment]
Please reopen if needed
