### ISSUE TITLE
net.launchpad.ulauncher is not registered as a .service

### ISSUE THREAD

**Issue by SkyzohKey** [Ulauncher/Ulauncher#214]
**Steps to reproduce:**
Type `ulauncher-toggle` in a terminal under Manjaro. Also returns the same as a hotkey.

**Ulauncher version**: v4.0.6.r1
**Linux distro**: Manjaro (GNOME) 17.1.3 x64 Linux
**Linux uname**: `Linux 4.14.16-1-MANJARO #1 SMP PREEMPT Wed Jan 31 2018 x86_64 GNU/Linux`
**Desktop environment**: GNOME 3.26.2

**Logs**:

```sh
[skyzohkey@skyzohkey-pc ~]$ ulauncher-toggle
Error org.freedesktop.DBus.Error.ServiceUnknown: The name net.launchpad.ulauncher was not provided by any .service files
```

**EDIT**: It does works when ulauncher is launched. Not when the program isn't started. Could we make it work even when the app is closed? ie. If Ulauncher is closed, open an show it, else just toggle.

**Comment by gornostal** [comment]
> It does works when ulauncher is launched. Not when the program isn't started. 

Yep. That's by design.

> Could we make it work even when the app is closed?

That is possible, but I'm not planning on doing that. Sorry.
A solution that I see is a bit hacky and I don't really want to include any workarounds into Ulauncher code unless they are very important.

**Comment by SkyzohKey** [comment]
This is very important because the user expect the app to be always here when it does press the keys. Your app is a productivity app. It needs to be accessible at any time. So it must be self healing :)

**Comment by gornostal** [comment]
But you can enable "Launch at Login" in Preferences.
Or I don't understand your use case?

**Comment by HoroTW** [comment]
Sure, lets me describe my case: 
I don't know why, but sometimes ULauncher crashes and then my hotkey for showing it does not work... 
I could configure it as a service that is automatically restarted on crash but I figured that a hotkey would be enough...
Since the toggle does not start it when it is not running (one could say it fails to toggle it - since it was hidden/closed and now it is still not there? :sweat_smile: - but whatever I'm also fine if the @gornostal does count this as hacky)

Solution:
Since I use an external hotkey to toggle ulauncher I just check for the "ServiceUnknown" ( == no instance running) and if so start it:
```
ulauncher-toggle 2>&1 | grep -o "ServiceUnknown" && ulauncher
```
ULauncher returns exit code 1 in two cases.... On window hide/close using toggle... and on errors... :/
Thats why the redirect of std:err and the grep is needed.
I think that this double reuse of exit code 1 is an issue, and should be fixed. (but for now this workaround is good enough ^^)


Certeinly a little hacky but perfekt for the way I use it ;)
