### ISSUE TITLE
Improve fuzzy search

### ISSUE THREAD

**Issue by FreshJR07** [Ulauncher/Ulauncher#232]
If I type in fire into the search I get the following results:

1) Files  
2) Firefox
3) Font Viewer

Why is a direct match below a partial match??

--

Side question, is there anyway to enable simultaneous directory & app search?

**Comment by gornostal** [comment]
About fuzzy search, that's a valid point.
I know it sometimes shows results in an unexpected order. That's because my algorithm is not perfect.
I'll add this to the list of improvements.

> Side question, is there anyway to enable simultaneous directory & app search?

I'm afraid it's currently not possible. Ulauncher doesn't have directory search -- it has a directory browser. That means I'm not indexing files on your computer.

I don't want to change anything about that, because I want Ulauncher code to be as simple as possible, so I can support and maintain it myself.

**Comment by gornostal** [comment]
I don't remember if I looked into fuzzywuzzy when I implemented fuzzy search. Thanks for the suggestion.
I'll check it out

**Comment by raddessi** [comment]
I set up a pull request that has the code swapped out here https://github.com/Ulauncher/Ulauncher/pull/317 

This seems to fix the odd matches I would get from time to time.. but I should test some more. I'll let you know if anything odd pops up. I did drop the min_score as well so it would match 2 character patterns, like 'fz' for FileZilla.

The requirements.txt would still need to be updated, along with anything else I missed.

**Comment by gornostal** [comment]
Thanks for the PR.

This is not an ideal time for that kind of changes because we are working on migration to python 3 and any change to the existing code create additional work of merging and testing code.

Besides, it's actually a bit more complicated to switch to fuzzywuzzy. First, dependencies are defined in distro-specific files like debian/control, setup.cfg, and PKGBUILD.template (not requirements.txt. That's only for dev and CI dependencies).

Plus, there are tests for that feature (`test_fuzzy_search.py`). You can check if they pass.

I can let you know once we are ready to accept changes to search functionality.

Meanwhile, you can use fuzzywuzzy locally. If you see any issues with that please let me know in the comments here. I am interested to know how well it works compared to the existing approach.

Thanks

**Comment by raddessi** [comment]
Gotcha, can do :)

**Comment by gornostal** [comment]
Hey @raddessi 

How is it going with fuzzywuzzy. Is it working better than the current logic in Ulauncher?

**Comment by raddessi** [comment]
Unfortunately I haven't done any more work on it since your last comment, the matching does seem to actually pick the correct items (for me at least) but I had the issue that I commented on in the PR that the best match wasn't number 1 on the list. I never got around to reading in to it more why that would be the case :/

**Comment by raddessi** [comment]
Hey nice! I see you just pushed out 5.0, I'll try that out and see if there are any differences still. If there are do you want me to put any effort in to getting the tests to pass or are you still thinking about design here?

**Comment by gornostal** [comment]
> if there are any differences still
There is no difference in terms of fuzzy search.

Tests are important because we should now if and how the search behavior changes.

**Comment by raddessi** [comment]
For sure, great point. I'll square everything up then

**Comment by voidstarstar** [comment]
@gornostal Why not just sort all matching results by how frequently they are used?  This would give each user a customized experience that learns from their behavior.  I think this is similar to the behavior of some other launchers (e.g. Gnome-Do).  Isn't a frequency database already being created to populate the frequent apps list anyway?

I would suggest the following:
Each time the user opens a program, a frequency counter associated with the program is incremented in a database.  When a user types a search string, gather all results using the current fuzzy search and sort them by decreasing frequency.  If there are ties, break them by using the same order you currently use now.  The `sort()`/`sorted()` functions are stable, so they should be able to do this.  Just sort the fuzzy search results where the `key` is a function that returns the corresponding frequency in the database (or 0 if the program is not in the database).  (If the database is very large, then performance may be an issue, in which case there are more efficient algorithms to sort and retrieve just the top results, however I don't predict performance will be an issue for a typical user.)

The nice thing is that this is independent from the fuzzy search algorithm used, so it can still be changed if the results are better.

**Comment by friday** [comment]
This was improved in 5.12.0, that was just released for Arch and Ubuntu/Debian packages. The Fedora build will be released soon too.

It's not perfect, but much better imo. Will keep this issue open.

**Comment by friday** [comment]
> Is that an issue with my extension not pre-sorting results or the launcher not sorting quite right yet? Is now a better time for a PR? I might be able to find some time to poke at it.

I think #824 should fix this.

**Comment by friday** [comment]
This will be fixed in the Ulauncher v6 branch (which has PR #827). It won't be released for a while, but we made a tracking issue if you want to be notified #869
