### ISSUE TITLE
Recommendation: Show favorite apps

### ISSUE THREAD

**Issue by JustPerfection** [Ulauncher/Ulauncher#238]
I want to have all of my favorite apps that pined on GNOME shell. I want to use it instead of "Show frequent apps". Is there any tweak that I can do to achieve that? or can you add it to the next update?

**Comment by gornostal** [comment]
Sorry, I'm going to have to close this issue because I'm not planning to implement this feature. And there is no workaround to display favorite apps in the current version of Ulauncher.

I want to keep the app simple so it's easier for me to maintain and support it. I'm now focusing on improving existing features rather than adding new ones.
