### ISSUE TITLE
Error when launching an Software Sources app: "Refusing to render service to dead parents". Linux Mint

### ISSUE THREAD

**Issue by ghost** [Ulauncher/Ulauncher#254]
**Steps to reproduce:**
Have a system with Mint 18. Upgrade in-place to Mint 18. Try to launch Mint's 'software sources' and see that the program does not launch.

**Ulauncher version**: 4..1.0.r1
**Linux distro**: Mint 19
**Desktop environment**: Cinnamon

**Logs**:

https://gist.github.com/CottonEaster/2250882fa33d2442c14eb453b15bd580

EDITED.

**Comment by gornostal** [comment]
You mean "software sources' appears in Ulauncher search results but when you select it nothing happens?
If so, could you grab the log file after you do that please? That event was not captured in the logs you linked in the description.

**Comment by CottonEaster** [comment]
Yes, or rather the relevant icon appears in my dock for a moment, and nothing else happens.

The log produces this when I try to launch the MintSources program: 'Refusing to render service to dead parents.'

Perhaps the following is helpful to note. The command that runs when the MintSources program is run from somewhere other than the launcher is: `pkexec mintsources`.

**Comment by gornostal** [comment]
Hmm, that looks like an error from the app that you are trying to run.
Will the app run if you select it in the Cinnamon's default launcher?

**Comment by CottonEaster** [comment]
> Will the app run if you select it in the Cinnamon's default launcher?
Sorry - I should have said. The answer is: yes, without any problems.

**Comment by gornostal** [comment]
I was able to reproduce that. I also found a cause https://askubuntu.com/a/721075
I guess that is fixable.

Meanwhile you can modify Exec line in the desktop file (mintsource.desktop) to 
```
Exec=sh -c "pkexec mintsources"
```

**Comment by CottonEaster** [comment]
OK, I had two mintsources (note: 'source_s_', not 'source') and I modified their exec lines as you suggested and now ULauncher can launch mintsources. Thanks! It would help people on Mint were you to fix this at your end.

**Comment by gornostal** [comment]
That is something I plan to do. Not sure when though.

**Comment by CottonEaster** [comment]
Some sort of milestone for the fix would be welcome (!).

**Comment by gornostal** [comment]
@CottonEaster sorry, I don't have a milestone or specific date by which that improvement will be implemented.

**Comment by goodwillcoding** [comment]
@CottonEaster if you can find out how Mint launches an item like this in their launcher it will help a fix on this end. Also can you post the original .desktop file that was causing the issue?

**Comment by CottonEaster** [comment]
@ goodwillcoding 

> if you can find out how Mint launches an item like this in their launcher it will help a fix on this end.

I believe I gave the answer above. That answer is: via `pkexec mintsources`.

> Also can you post the content of the original .desktop file that was causing the issue?

By default it is that same command - `pkexec mintsources` - that the desktop launcher runs too.

**Comment by goodwillcoding** [comment]
@CottonEaster to clarify I meant the code in the launcher itself that handles pkexec without having the dead parent issue, seems like they do something.

**Comment by Sraw** [comment]
Honestly, I think this issue is unsolvable for Ulauncher.

The reason why launching from menu doesn't have this problem is because they really have parent, their parent is the `cinnamon` itself.

While the applications launched by Ulauncher don't have parents, their parents are PID 1.

It is actually easy to solve this issue, just launch the applications as child processes. But we all know this is unacceptable...

**Comment by friday** [comment]
I think release 5.12.0 fixed this. The way apps are opened now is with systemd-init and a different croup. This issue is old and stale, so rather than asking for confirmation, please let me know if I'm wrong, and I'll reopen it.

**Comment by gritty-gitty** [comment]
This is still an issue in Linux Mint 20.3 which I just upgraded to from 18.3. The fix is easy though: It is sufficient to put a [front end to pkexec](https://gist.github.com/gritty-gitty/0de1833302bb20fde79394abd6b6762d)  as an executable into the owner’s private bin in ~/.local/bin/ .

The latter directory is, at least in newer distros, in the path already (cf. /etc/skel/.profile). If not, add it in at the end of ~/.profile — it’s needed anyway by some Ulauncher extensions that install additional python modules locally.
