### ISSUE TITLE
Create script to make .rpm builds

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#27]
Does rpm-based systems have something like Launchpad for Debian-based ones?
Would be great to use something like that.

**Comment by geckolinux** [comment]
Hi, have you considered the [openSUSE Build Service](http://build.opensuse.org/) for this?

**Comment by Abhinav1217** [comment]
Just came here via a blog article. Would love to get this on Fedora. I am looking for a replacement for Synapse since it is not working properly on wayland.
  
I would recommend https://copr.fedorainfracloud.org is very similar to launchpad for RPM distros. It can take source code and make file to create rpm repo which can be used by `dnf`, `yum` to install and update. Just like ubuntu ppa. 

In past I have successfully used https://github.com/jordansissel/fpm . It will easily create rpm, deb, etc packages for a lot of different distros. only drawback is that it just does packaging. So updates is done by downloading new builds, or if your app have inbuilt  updating system. Using system package manager is not an option unless you host PPA and COPR yourself 

OBS is good, but latest distros are not available for a long time. For example, Fedora 25 is still not available for build. This is why I don't recommend it.

Then there is https://packagecloud.io/ which I am currently testing for my need. It will create package and repos for multiple distros. and it is free for opensource project ( monthly bandwidth is limited ). http://pulpproject.org/ is open source, self hosted alternative.

And Last mention, Appimage, Flatpack, Snap, all are now popular. Appimage is best in terms of simplicity, and all distros have support for it. Snap, Flatpack on other hand need user to install a runtime. Snap developers mainly focus  on Ubuntu, so it is losing to Flatpack.

Looking forward for official RPM release. I will try to build from source for now. Quick question, Does it have simple calculator and converter in it. Like `ctrl+space` and type `2+2` and it will show `4` in output?

**Comment by gornostal** [comment]
Wow, thanks for the recommendations @Abhinav1217.
I'm trying Snap, but it has some bugs. I'll take a look at Appimage, Flatpack.

It has calculator. It works just as you've described.
It doesn't have unit converter.

**Comment by Abhinav1217** [comment]
I installed it from source, last night and spent few hours with it. Only issue so far is that it doesn't stay running in the background. Maybe because of wayland, or I didn't properly build it, I don't know. A better configuration option would be great. I must say its speed is good. 

I didn't get predictive selection in it,  Did i build it wrong or is it still on roadmap.  

Try Appimage, It is older and have really good community behind it. Gnome and KDE has improved integration of flatpack in core but still package size was smallest and simplest in appimage.

**Comment by gornostal** [comment]
AppImage is great, but it's far from a straightforward solution that I am looking for.
I've tried to wrap my head around it yesterday and came to a conclusion that in order to build a simple GTK app in Python it takes a lot of time and obscure workarounds. Don't like that.

I'm not sure what it will be in the end, but in the short run I'm planning to create a tar.gz with all the python files + a shell script with `apt-get/yum/etc. install ...` to install deps for different distros.

**Comment by gornostal** [comment]
RPM builds for Fedora and SUSE are ready. Download links here http://ulauncher.io/#Download

AppImage is still on my roadmap though.

**Comment by geckolinux** [comment]
Very nice, testing the openSUSE RPM now. Thanks a lot!

**Comment by Abhinav1217** [comment]
Just installed again from rpm. Loving the RPM, Thanks. 

Installation is perfect and app is perfect too.  I am not getting those two errors I mentioned before from installing via rpm so its a plus.
