### ISSUE TITLE
Feature: Support keywords in search

### ISSUE THREAD

**Issue by ivashin** [Ulauncher/Ulauncher#270]
Many applications provide additional keywords in their .desktop files to facilitate finding them. E.g. if you type "Excel" into Unity Dash it shows LibreOffice Calc because libreoffice-calc.desktop contains "Microsoft Excel" in Keywords section.

It would be very useful to parse these keywords and use them in search similarly. https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys contains specification details.

It also makes to include comment from desktop entry in search as well, albeit perhaps with a lower priority.

**Comment by friday** [comment]
This one is important to me as well. Part of what I expect the launcher to handle is to find the apps I rarely use and don't remember the name of. For example I search for "usb" not specifically the name "Etcher" or "UNetbootin" since I use these apps too rarely to remember.

**Comment by gornostal** [comment]
Yes, that sounds like a nice feature to me too.

**Comment by friday** [comment]
Comment aka "Description" (it's the same thing) is now supported in the Ulauncher v6 branch, so I'm renaming this to remove that. Keywords work a bit different from this and need to be matched on a word by word basis.

**Comment by friday** [comment]
I should clarify why this isn't something I am looking into implementing, or at least not soon:

Implementing this would make searching more complex, slower (maybe not noticeably so though) and give you false positives you didn't intend to match based on keywords.

Many of these apps have a lot of keywords. Gnome Online Accounts (settings panel) for example has these: `Google;Facebook;Twitter;Yahoo;Web;Online;Chat;Calendar;Mail;Contact;ownCloud;Kerberos;IMAP;SMTP;Pocket;ReadItLater`
So if you search for Chat or Mail or Calendar or "Pocket" you match that. In some cases that will be helpful. In some cases not.

Gnome lock panel has these: `screen;lock;diagnostics;crash;private;recent;temporary;tmp;index;name;network;identity;privacy`

XFCE WMTweaks has these: `windows;behaviour;settings;preferences;cycling;cycle;switching;focus;raises;accessibility;key;dragging;move;moving;hide;frame;title bar;maximized;tile;screen;edge;hot corner;snapping;mouse wheel;roll up;workspaces;placement;compositor;compositing;enable;disable;shadows;decorations;opacity;resize;inactive;preview;compiz;transitions;`

As for Performance, the matching and scoring part of the search would take much longer because it needs to check all these keywords of every app. Maybe this will be ok, but it remains to see. Our fuzzy search in v6 is very well tuned and smart, but it might not be as fast with all these keywords added.

In our current search we make the assumption that you are matching your input query as a while (including spaces and special character) with the app names. We don't break apart into words and compare each word. We can support descriptions also, in which case we match with whichever one is most similar. But for keywords you probably expect the query to be split into words and doing an inclusive search (like google search). You want to search for "Usb flasher" for example to match both keywords, or if the app is named "Flasher" and it has a keyword "usb". This is complicated, and especially all this work which might not even improve the behavior overall for supporting this issue.

Additionally people will file bugs like #816 if the search results are determined and sorted by parameters they can't see (#816 is actually a feature, but not tuned well).

**Comment by friday** [comment]
Added via #1012 to the v6 branch. This implementation only matches one keyword at the time, so it seemed to me like a reasonable middle ground, but it takes some real word tests and usage to know.

v6 won't be released for a while, but we made a tracking issue if you want to be notified #869
