### ISSUE TITLE
Feature request: Always show Ulauncher on the desktop.

### ISSUE THREAD

**Issue by Maccer1** [Ulauncher/Ulauncher#274]
It would be nice if Ulauncher always appeared on the desktop when I minimize all my other apps. I'm not sure if this is possible but it would be great to have it nonetheless.

**Comment by gornostal** [comment]
Hi @Maccer1 
Thanks for your feature suggestion. Unfortunately I'm not planning on adding this feature.

There are two reasons for that:
1. I want to keep the app simple and include only features that most of the users are going to use
2. I want to have as less code in Ulauncher as possible in order to have as fewer bugs as possible, so I alone can handle all the bug reports.

Hope you'll understand. Closing this issue now
