### ISSUE TITLE
System Settings can't index in search

### ISSUE THREAD

**Issue by Abtektas** [Ulauncher/Ulauncher#296]
**Steps to reproduce:**
_your steps to reproduce here_

**Ulauncher version**: v4.3.0.r2
**Linux distro**: Ubuntu 18.04.1
**Desktop environment**: Gnome

**Logs**: i

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_ https://gist.github.com/Abtektas/22a56329e53bb4e20e0b9d39be0f3337

When I searching one of the system settings(e.g. displays, sound...) it's not coming/indexing.

**Comment by friday** [comment]
It's because they are disabled from search (NoDisplay=true)

You can find an extension for this and all the info you need + more here:
https://github.com/friday/ulauncher-gnome-settings

I actually don't use it myself. I use this method instead: https://github.com/friday/ulauncher-gnome-settings#create-or-modify-desktop-entries

**Comment by Abtektas** [comment]
I couldnt remember when but i used to access the settings :/ Anyway thank you for the extension, it helped :)
