### ISSUE TITLE
Store themes and .db files in ~/.local/share/ulauncher

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#347]
See https://github.com/Ulauncher/Ulauncher/issues/152#issuecomment-462654460

Basically, deleting the cache dir should not change Ulauncher behavior. Not it changes it because the .db files with user patterns are stored in there.

**Comment by kisaragi-hiu** [comment]
IMHO, extensions should not be stored in `~/.cache` either.

Browsers treat downloaded websites as cached data because it is unfeasible to store all websites the user visits on disk: it'd take up too much space, and much of it will rapidly become outdated. The download bandwidth saved isn't worth the space required.

Ulauncher extensions are not like that: the saved download bandwidth *is* worth the space required. They are not updated rapidly (more bandwidth saved), and when added up they don't take up as much space as websites (not much space is required). This makes it reasonable to store them as persistent data, not cached.

**Comment by gornostal** [comment]
Implemented in 5.3.0
