### ISSUE TITLE
Allow all keys as shortcut

### ISSUE THREAD

**Issue by 13hannes11** [Ulauncher/Ulauncher#366]
Hi, I would like to bind whatever keys I like as hotkey. My thinkpad t450s has a search key and I would like to use this one to bind to be used.

**Comment by gornostal** [comment]
hi @13hannes11 

You can bind any hotkey your OS that allows you via OS settings.
But instead of binding a key to execute `ulauncher` command, use `ulauncher-toggle`.

See this as an example of how to bind keys in Gnome running in Wayland https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland
