### ISSUE TITLE
Error when download extension behind proxy server

### ISSUE THREAD

**Issue by pydawan** [Ulauncher/Ulauncher#408]
Hello guys.

I can't download Ulauncher extensions behind corporate proxy server.

**Comment by gornostal** [comment]
@pydawan make sure you have proxy configuration set in your environment variables https://wiki.archlinux.org/index.php/Proxy_server#Environment_variables

If that doesn't help, you can manually download extensions from Github and put them into `~/.cache/ulauncher_cache/extensions/`. Just make sure you download the right version that matches API version of Ulauncher

**Comment by ogulec** [comment]
I have similar error when I try to add extensions, it gives me `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>`
I gave up searching solutions for this problem, I guess this is a common ssl problem for linux mint 18.3 because I can not install spicy applets to desktop also. 
Therefore, I try to install extensions manually bıt there is no extensions folder in `~/.cache/ulauncher_cache/`. I created and downloaded the right version of an extension to this folder but not shown in the list. Refresh button is not working as well.

**Comment by compilelife** [comment]
> @pydawan make sure you have proxy configuration set in your environment variables https://wiki.archlinux.org/index.php/Proxy_server#Environment_variables
> 
> If that doesn't help, you can manually download extensions from Github and put them into `~/.cache/ulauncher_cache/extensions/`. Just make sure you download the right version that matches API version of Ulauncher

According to the source code, it should be `$xdg_data_home/ulauncher/extensions`.

To decide what xdg_data_home is ,check this: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

For me, it's `$home/.local/share/ulauncher/extensions`
