### ISSUE TITLE
The extension server generates CPU wakeups when idle

### ISSUE THREAD

**Issue by guncha** [Ulauncher/Ulauncher#410]
### Steps to reproduce
1. Start `ulauncher`
2. Start `powertop` and observe wakeups for the above process

### Current behavior

It hovers around 10 wakeups per second even when the main window is not visible.

### Expected behavior

The process should not use any resources when idle. If I start it with `--no-extensions`, the process doesn't even show up in the PowerTOP list because it's barely using any resources.

This is the likely culprit:
https://github.com/Ulauncher/Ulauncher/blob/dev/ulauncher/utils/SimpleWebSocketServer.py#L586

The `SimpleWebSocketServer` has a default `selectInterval=0.1` param that gets used to poll on the `select` calls later in the file. There's probably a reason for it that I'm not qualified to comment on, but at least on my system setting that to 0 or disabling the extensions altogether (I'm not using any) resulted in significant battery life savings, so it could be worth looking into. 

### Environment
**Ulauncher version**: 5.2.0 (https://aur.archlinux.org/packages/ulauncher)
**Linux distro**: Arch
**Desktop environment**: Metacity

**Comment by gornostal** [comment]
That's a good find @guncha 

`--no-extensions` flag actually means `don't start extensions automatically` and it is used by extension developers to run extensions manually for debugging purposes. That's why the WS server starts even if `--no-extensions` is passed.

I'll think how the issue can be fixed. Probably by introducing a new command line argument that disables the WS server

**Comment by friday** [comment]
This will be fixed in the Ulauncher v6 branch, as this branch has completely rewritten this part or the app (no more websockets). It won't be released for a while, but we made a tracking issue if you want to be notified #869
