### ISSUE TITLE
Open urls directly

### ISSUE THREAD

**Issue by KuenzelIT** [Ulauncher/Ulauncher#413]
Hi,

I was using Albert for quite a while and a very useful feature is opening urls directly instead of using the default search engine. So what I want to suggest is that if a url is identified (query ending with '.com' or '.org', ...), then Ulauncher should suggest to open that url directly in my browser.

I assume this is not possible by creating an extension, since extensions always need a keyword?

**Comment by friday** [comment]
You can make a shortcut for this, and it would work the way you want some of the times. Shortcuts will show up if your input doesn't match any app, extension or other shortcuts prefix.

Since searches are fuzzy it's likely they will match something of the url is short though.

The way the calculator and folder browser are implemented is exclusive, so any input that matches mathematic expressions or path names (beginning with `~`, `/`, or `$HOME`) will bypass the normal matches. It wouldn't be safe to implement this for inputs ending with ".com" etc since there's countless top level domains, but full links with protocol (`https://...`, `http://...` or `ftp://...`) would probably work (if @gornostal wants to support this).

**Comment by KuenzelIT** [comment]
Is it possible to disable fuzzy searches (maybe in the future)? Then I assume shortcuts would work quite well.

I really like Ulauncher a lot, it looks very nice and has a good architecture. There are just a few things that would make it even more awesome.

**Comment by gornostal** [comment]
I prefer keeping Ulauncher simple. 

@KuenzelIT What you've described can be implemented with shortcuts as @friday has suggested. If you set one character for an shortcut trigger (for example `w`), you type in `w website.com` and it opens your website.
