### ISSUE TITLE
String shortcuts and extension keywords in one query

### ISSUE THREAD

**Issue by papermache** [Ulauncher/Ulauncher#425]
### Describe the solution you'd like

I would like to call the URL shortcut using keyword "u" with Chrome Profile extension keyword "b" to open a url with a selected profile.

**Comment by gornostal** [comment]
@papermache I assume this request is related to your comment here https://github.com/Ulauncher/Ulauncher/issues/407#issuecomment-529217968? 

If so, in order to do that with Ulauncher shortructs you will need to figure out how to parse strings in bash or any language of your choice.

Please reopen if I didn't get the idea of this feature request.
