### ISSUE TITLE
Arch Support

### ISSUE THREAD

**Issue by lucasnota** [Ulauncher/Ulauncher#48]
I would like use it in Arch,

**Comment by djendreizak** [comment]
As far as I know it's planned for 2.0. You can try to build it manually via install_deps

Take a look:
https://github.com/Ulauncher/Ulauncher/blob/dev/install_deps

**Comment by Cross03** [comment]
Some dependecies are not even listed in Arch linux , can any one figure out what is those packages name in arch linux :
error: target not found: python-pysqlite2
error: target not found: gir1.2-gtk-3.0
error: target not found: libgtk-3-0
error: target not found: gir1.2-keybinder-3.0
error: target not found: gir1.2-webkit2-3.0
error: target not found: libkeybinder-3.0-0
error: target not found: gir1.2-glib-2.0
error: target not found: gir1.2-gdkpixbuf-2.0
error: target not found: gir1.2-appindicator3-0.1

**Comment by hughwilliams94** [comment]
- python-pysqlite2 = `python-pysqlite`
- all gir... packages are in `gobject-introspection`
- libkeybinder-3.0-0 = `libkeybinder3`

Having said this I have installed all dependencies and still can't get it to run. Encountering  lot of python errors!

**Comment by Cross03** [comment]
After encounter a lot of python errors, i realize that the problem is this software written mainly in python2 where in arch linux the default python version is python3. So to run the "run" file i must change the  line 1 and 20

**line 1 : **
change python to python2
**line 20: **
add python2 in the beginning of the line

**the launcher runs, but no matter what i type-in there would be no changes. the settings and tray works.**

![selection_057](https://cloud.githubusercontent.com/assets/16729502/23112088/d375348e-f75f-11e6-98e2-e18ec2e7978d.png)

**the preferences**

![selection_058](https://cloud.githubusercontent.com/assets/16729502/23112096/ef56ed32-f75f-11e6-8645-7ec4eb46a38c.png)

**but this is the error message that i got:**
 
File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4

**Comment by gornostal** [comment]
I'll take a look at the pickle error.
Thanks for reporting.

**Comment by hughwilliams94** [comment]
The pickle error is related to python2/3 issues as the highest available protocol in python2.7 is 2.

**Comment by gornostal** [comment]
@Cross03 try deleting files from `~/.config/ulauncher` and `~/.cache/ulauncher-cache`. 
Then once you restart the app it sold create pickle files with the correct protocol.

**Comment by Cross03** [comment]
@gornostal  Dude, that solve the problem. This software is awesome.

**Comment by gornostal** [comment]
@Cross03 no problem)
Thanks @hughwilliams94 for the hint.

**Comment by gornostal** [comment]
Guys, 
I would greatly appreciate if someone could provide a Virtualbox image of Arch + Gnome.
I want like to test Ulauncher on it.

**Comment by mmetak** [comment]
I made a quick pkgbuild file for arch if anyone is interested?
https://aur.archlinux.org/packages/ulauncher-git/

**Comment by gornostal** [comment]
That's super cool!
I just was going to try Arch Linux and see how to packaging can be done there.

I'm new to Arch so if you have some time to answer several questions about how you packaged UL that would be great.
I'm available here https://gitter.im/Ulauncher/General

**Comment by gornostal** [comment]
Arch Linux is officially supported https://aur.archlinux.org/packages/ulauncher/
`git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is`

**Comment by Dmendoza99** [comment]
@motangpuar in what file do you mean we should do that changes

**Comment by letroll** [comment]
Hello,
It's not working anymore on archlinux. My app *.desktop in /usr/share/applications/ are not used

**Comment by gornostal** [comment]
hi @letroll I've just tried on my Vbox with Manjaro and it works. I see no problems with /usr/share/applications/

If this issue is still actual, could you create a bug following the bug report template please?

I'm closing this thread
