### ISSUE TITLE
Mutliple hotkeys for multiple contexts/scopes

### ISSUE THREAD

**Issue by owzim** [Ulauncher/Ulauncher#527]
### Is your feature request related to a problem? Please describe

Examples:

`alt`+`space` for everything
`alt`+`shift`+`.` for a certain extension only (so no need to trigger with a keyword)
`alt`+`shift`+`w` for web searches

So there is one regular hotkey for everything and additional (optional/configurable) hotkeys for specific searches, bound to an extension.

### Describe the solution you'd like

Every scope could have a configurable icon

**Comment by friday** [comment]
Related issue: #312

**Comment by gornostal** [comment]
I'd prefer to keep one hotkey in settings because it's really hard to manage it.
Once #312 is implemented you can use `ulauncher-toggle` command in combination with OS native hotkey settings to achieve what you need.

Make sure you subscribe to updates in #312 to keep track of its status.
I'm going to close this one.
