### ISSUE TITLE
Abnormal virtual memory usage after clicking ulauncher settings icon

### ISSUE THREAD

**Issue by vgazioglu** [Ulauncher/Ulauncher#570]
### Steps to reproduce
1. Launch ulaucher (ctrl-space in my case)
2. Click **settings** icon on the ulauncher window (top-right side)

### Current behavior
After clicking settings icon, ulauncher virtual memory usage shows a huge amount (_82,4 GB_ in my case) and then seems to continue to increase (memory leak)

- WebKitNetworkProcess
- WebKitWebProcess 

Above two processes are the same (Those processes starts  after clicking)

### Expected behavior
Normal virtual memory usage

### Environment
**Ulauncher version**: 5.7.5
**Linux distro**: Kernel: 5.3.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
**Desktop environment**: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

### Logs
https://gist.github.com/vgazioglu/d287535dde6ad71b967a817a73354913
-->

**Comment by friday** [comment]
Personally I think WebkitGTK is a bad solution/API and I want to remove that whole part of Ulauncher, but a quite substantial amount of work would have to be done for that, to the degree I though a full rewrite would make more sense.

`WebKitNetworkProcess` is kept running forever as long as the main loop is running, so the only way to get rid of that is moving the preferences to it's own isolated process with an isolated main loop. I would definitely be in favor of that if someone else did the work, but it would be a lot of work because it directly communicates with the main Ulauncher window now.
`WebKitWebProcess` is the actual Webkit webview the preferences is rendered to and it would be freed up if we closed the preferences normally, but we don't. We keep it running and hide it, so that it will load faster the next time. This is not a choice I made, nor feel happy about, but changing it would require some architectural changes to how the Python app and Webkit app communicate. Because WebkitGTK doesn't let you destruct this and setup new with each new instance of the same window. It can only be set up once.
