### ISSUE TITLE
comma as decimal symbol

### ISSUE THREAD

**Issue by RobRobM** [Ulauncher/Ulauncher#575]
Right now the calculator only works when using the . as the decimal symbol.

Request to have the option to use the comma as decimal symbol as when using the keyboard. When using the numeric pad the use of the . should still be considered as the decimal symbol.

**Comment by nishp77** [comment]
I think this shouldn't be the case however may be outwards when entering large amounts the comma would make sense, also to show the result if it's a big number then we can use comma. However for the decimals value I don't think we should use it. This is my take though.

**Comment by friday** [comment]
Ulauncher doesn't know which keyboard keys you're pressing. Only the letters they're producing.

The suggestion in #786 to use the locale is better imo, but hard to implement, and questionable if it's even something we want.

**Comment by astroty** [comment]
Sorry about the duplicate

Why would this behavior be questionable?

**Comment by friday** [comment]
The current implementation is just 68 lines of code and works for everyone. It's using dot as decimal separator because Python (as all other programming languages) uses the US standard for these things. Supporting more options has no simple one size fits all type of solution that doesn't add complexity or gotchas. If we do it your way, we break someone elses preferences. Locale is tricky, and only two people wanted this so far, so it doesn't seem very important to people.

Both me and the author are European, so our locales should say that we use comma as decimal separator. I'm used to both in different contexts, and actually recall trying to use comma in Ulauncher a long time ago, but learning not to, and I prefer dot now.

**Comment by friday** [comment]
This is now supported in the Ulauncher v6 branch, going with a simple approach by accepting either dot or comma as decimal separators and not accepting any thousand separators in the input.

V6 won't be released for a while, but we made a tracking issue if you want to be notified #869
