### ISSUE TITLE
Ulauncher minimizes on losing focus

### ISSUE THREAD

**Issue by fabubaker** [Ulauncher/Ulauncher#58]
I've set my mouse focus mode to be`sloppy`, a.k.a when the cursor is moved out of the application's window, that app loses focus (the default would be clicking on another app's window to lose focus).

This setting drives Ulauncher crazy, often minimizing itself before I can select what I want.
Is this a GTK issue or is there a setting that disables the minimizing?

**Comment by gornostal** [comment]
I'm not sure about that.
How do you change mouse mode to `sloppy`?

**Comment by fabubaker** [comment]
Here's a gif of what happens when I move the cursor outside of the Ulauncher UI.

![output](https://cloud.githubusercontent.com/assets/9405286/23106450/b6bb6b00-f6bb-11e6-964d-de2a529ced87.gif)

The issue is that when I open Ulauncher and my mouse isn't inside the launcher's window, it just closes after 2 or 3 keystrokes.

My bad about not being clear what `sloppy` is, it's a setting in Unity that allows you to switch focus from one window to the other without clicking on the other window. It's also called `focus follows pointer`.

**Comment by gornostal** [comment]
This seems like a valid bug then.
I need to know exactly how to reproduce this behavior.
Is [this](http://askubuntu.com/questions/64605/how-do-i-set-focus-follows-mouse) the accurate instruction on how to get a sloppy cursor?

**Comment by fabubaker** [comment]
Yep it is!

**Comment by gornostal** [comment]
Hi @fabubaker 

I've taken another look at this issue. 
I cannot exactly reproduce the behavior you described:

> The issue is that when I open Ulauncher and my mouse isn't inside the launcher's window, it just closes after 2 or 3 keystrokes.

If I leave the cursor over the input of UL or completely outside its boundaries, everything works fine for me.
However, if cursor happens to be outside of the UL frame, then inside it, then again outside, focus will be lost by UL and the window gets hidden. That is by design.

I linked a recording bellow where I'm tying something that produces 8 result items, cursor becomes inside of the UL boundaries, then I type in more to get 1 result item then the UL window hides.

https://dl.dropboxusercontent.com/u/10361250/tmp/Screencast%202017-02-26%2020%3A13%3A05.mp4

Are you experiencing different behavior?

**Comment by gornostal** [comment]
Closing as there was no response

**Comment by fabubaker** [comment]
Hey @gornostal. Apologies for the late response. 
It pretty much behaves the same way as you showed, however, in my case, when I open Ulauncher, and the cursor is somewhat far away from the UI, it closes immediately after I type in a few words.

However, I am not too sure if it is your recent commits, but this issue seems to have been fixed. :smile: 
This makes me Immediately switch from Synapse to Ulauncher!

**Comment by gornostal** [comment]
Happy to hear that :)

**Comment by imtiazsakib** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16275349/54860774-05ba4680-4d5a-11e9-98bd-8c5091eb4ae0.gif)

This is how it closes when the search result gets narrowed down and leave the cursor. I am using version 4.3.1.r4-1 from AUR.

**Comment by gornostal** [comment]
hi @imtiazsakib 
If you're using i3wm, this comment may help you https://github.com/Ulauncher/Ulauncher/issues/337#issuecomment-456497810
