### ISSUE TITLE
Feature request: make width & heigth configurable; keep focus

### ISSUE THREAD

**Issue by zz0rk** [Ulauncher/Ulauncher#585]
Please add an option to make width & height of Ulauncher window configurable from settings.
Please add an option for Ulauncher window to retain focus when desktop manager configured for sloppy raise window on mouse over.

Thank you

**Comment by troycurtisjr** [comment]
Note @zz0rk that starting with 5.9.0 there is now an option `Don't hide after losing mouse focus`, regarding your second item. Also generally it is best to have one request/issue per GitHub issue. On your first request, there appears to be an existing issue #561 regarding the configurable width. It would probably be better to include your interest in that issue instead of creating a new one.
