### ISSUE TITLE
IMPROVE: Basic integration with user's environment/OS

### ISSUE THREAD

**Issue by VladimirMikulic** [Ulauncher/Ulauncher#588]
Hi!

First of all, I would like to thank everyone that has been working on this project.
ULauncher is great and I love it but some critical things are missing.

For example, typing "reboot" or "shutdown" doesn't show up anything.
I would expect it to show entries for rebooting/shutting down the machine.

ULauncher doesn't show browser bookmarks/history either which I use daily. (probably others as well)

I am aware of plugins like `Run`, `System`, `Bookmarks` etc. but it's time-consuming to install them every time.
There is no "plugin store", a user needs to go to the website click "CTRL + F" (no search bar) and go to each one of them, copy link, paste it into ULauncher to install it.

Could this ecosystem be improved?

Thanks and keep rocking!

**Comment by troycurtisjr** [comment]
My personal opinion is that it is probably best to keep such functionality as extensions instead of in the core, that way it is opt-in when the user wants it. The more that gets added to the core ulauncher the more bloated it could become and the more likely that it is harder to trim it back or tweak behavior based on user preference. As extensions, the user could swap one system extension for another that behaves more closely to the way they would like it behave.

I do agree that the extension experience could be streamlined to make it easier to install. Do you have any specific ideas that would like to see with the extension experience? If things could behave exactly like you'd want, how would that look?

**Comment by VladimirMikulic** [comment]
Hi @troycurtisjr. I don't use ULauncher anymore, but built-in extensions store would be great.

**Comment by gornostal** [comment]
Hi @VladimirMikulic 

Thanks for showing the interest in Ulauncher.
Sorry, but I'm going to have to close this feature request. I want to keep ulauncher as simple as possible.

As for the plugin store, there are definitely a lot of areas of that could be improved, including the store. 
So, your request is noted. I'll create a separate issue in ext.ulauncher.io project once I define all the API and UI requirements for contributors.
