### ISSUE TITLE
Can I recognize and search even "comment" in ~/.local/share/applications/*.Desktop File?

### ISSUE THREAD

**Issue by opqriu** [Ulauncher/Ulauncher#613]
## Question
Can I recognize and search even "comment" in ~/.local/share/applications/*.Desktop File?
Is there a way? Is it possible on Ulauncher?

[Desktop Entry]
Version=1.0
Name=유튜브
Comment=**Youtube (Ice SSB Webapp)**

**Comment by friday** [comment]
They are displayed but you can't search them I believe. It would probably be too much information (and false positives) for the fuzzy matching.

**Comment by RedBearAK** [comment]
@friday 

> They are displayed but you can't search them I believe. It would probably be too much information (and false positives) for the fuzzy matching.

I'm bumping this issue in late 2021 because it's a close match for the situation I just encountered. Three bittorrent clients installed, but only two will show up in search results when typing "bittor" or "torrent", even though all three applications have identical description strings in the "Comment=" field of their desktop files, each containing the word "BitTorrent": 

`Comment=Download and share files over BitTorrent`

They also each have identical strings in the "GenericName=" field, containing the word "BitTorrent": 

`GenericName=BitTorrent client`

It's illogical to present the content of the "Comment=" field to the user but not parse that same string for keywords to help the user actually find the application. You can easily filter out overly common words like "and" or "the" if you're worried about cluttering the fuzzy search too much. 

The "GenericName=" field should also be parsed, it seems, and does not seem to be getting parsed for keywords by Ulauncher. 

All three of these apps do show up in the GNOME app search when typing "bittorrent". So the GNOME shell must be parsing either "GenericName=" or "Comment=" or both. 

The three apps are: 

Transmission
Deluge
qBittorrent

Transmission is the one that doesn't appear in Ulauncher when typing "torrent" or "bittor". Strangely, Deluge fails to appear in the GNOME app search when typing "torrent" but all three show for "bittorrent". Don't know what that's about. 

I don't have Albert launcher installed right now, but based on previous experience with using Albert I would expect all three of these apps to show for either of the search keywords mentioned above. 

In opposition to your own quote above from 2020, you agreed with the importance of having this as a feature in a launcher in this comment from 2018: 
https://github.com/Ulauncher/Ulauncher/issues/270#issuecomment-416041387

Attaching the desktop files for the three bittorrent client applications for reference: 
[Bittorent_clients_desktop_files.zip](https://github.com/Ulauncher/Ulauncher/files/7700390/Bittorent_clients_desktop_files.zip)

**Comment by friday** [comment]
This is now supported in the Ulauncher v6 branch (thank you again @BharatKalluri). V6 won't be released for a while, but we made a tracking issue if you want to be notified #869
