### ISSUE TITLE
Activate launcher on key up

### ISSUE THREAD

**Issue by ACheshirov** [Ulauncher/Ulauncher#626]
I noticed that the launcher triggers on key press.
Is there anyway to change this behaviour to "on key up".

I want to set the launcher to open just with Win (Meta) key and disable the standard one.
The main problem is that, when I press some shortcuts like Win + D (show desktop) that triggers the Ulauncher as well because it detects the meta key and prevents "shop desktop" shortcut to trigger up.

**Comment by troycurtisjr** [comment]
I think it is unlikely that ulauncher will attempt to directly integrate this and I'm not convinced it could even do so since it needs to either be given the key events or not. However I think you can probably accomplish what you want by following the instructions found in https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland. Even if you aren't on wayland. By configuring the shortcut directly in your desktop environment, it can have full knowledge of all the configured hotkeys.

**Comment by ACheshirov** [comment]
I have already done this via ksuperkey
