### ISSUE TITLE
Predictive selection doesn't work as expected

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#63]
@Abhinav1217 please tell what you type in, what you expect to see, and what you actually see.

**Comment by gornostal** [comment]
Please reopen if needed

**Comment by Abhinav1217** [comment]
It is less than hour since I installed the RPM, so I can't say much now. By predictive selection I mean that app should select the option I choose most. For example.

When I search 'Fi' I see three apps, Firefox, Files, Filezilla. in alphabetical order.
I choose Firefox 5 times, and choose Files 2 times. 

I expected to see order of apps in order of frequently used or last used with last used option preselected, so that I can just type 'fi' and press enter to access it.

I actually see only alphabetical order. With first option selected. 

I will run it for few hours and then let you know. It is persist, I will reopen.

**Comment by Abhinav1217** [comment]
By the way have a look at https://cerebroapp.com/ , it is on github. It is on nodejs but still fast. I know python webview is tough so kick the images and website previews for later. For now, go through the Plugin API  they have. Its nice. They have some nice plugins too.

**Comment by gornostal** [comment]
Thanks. I've installed the app. Testing its features...
