### ISSUE TITLE
CopyToClipboard does not work in ItemEnterEventListener

### ISSUE THREAD

**Issue by mikebarkmin** [Ulauncher/Ulauncher#662]
`CopyToClipboardAction` does not work for me when I run it in an `ItemEnterEventListener`. It does for example not work for Text Expander. Here is the line which runs the `CopyToClipboardAction` (https://github.com/brpaz/ulauncher-text-expander/blob/466ff956edcb0dfc22767800a9be78cc1f5a4d1c/main.py#L128). I have used the debugger and everything works fine, but nothing is stored in the clipboard, even though `out` contains the correct string.

If the `CopyToClipboadAction` is run directly from a `ExtensionResultItem` like in the Timestamp Macro extensions everything works fine (https://github.com/nurgasemetey/ulauncher-timestamp-macros/blob/c7e4f1079b3355b7dfe1bfa887dff9d756844fd3/main.py#L35). 

### Current behavior
CopyToClipboardAction does not work in an ItemEnterEventListener.

### Expected behavior
CopyToClipboardAction should copy to clipboard when run in an ItemEnterEventListener.

### Environment
**Ulauncher version**: 5.9.0
**Linux distro**: Ubuntu 20.04
**Desktop environment**: Gnome

### Logs
https://gist.github.com/mikebarkmin/cc49cbcfc947acaa3ae046383247e4a4

**Comment by friday** [comment]
Possibly related: https://stackoverflow.com/questions/15241203/effect-of-pygtk-clipboard-set-text-persists-only-while-process-is-running

The gtk clipboard API is a huge pain to work with imo.

**Comment by mikebarkmin** [comment]
I think I have found the issue. I think that the code should be implemented differently. Here you can see the diff of the old and new implementation of the copy to clipboard functionality of text expander. The new one works for me.

https://github.com/brpaz/ulauncher-text-expander/pull/15/commits/7860d2de2822fbe81160554ad894fbfcd4b12c34

The difference is that one should not run `CopyToClipboardAction(out).run()` but should return `CopyToClipboardAction(out)`. This also requires that the `ExtensionCustomAction` should be keeping ulauncher open (`keep_app_open=True`).

**Comment by friday** [comment]
I never looked into this in details since I had my own issues with this GTK API (not the Ulauncher implementation of it). Seeing your last comment now it was indeed an extension implementation error, but it could also be thought of as confusing API. 

Extensions should indeed not run `...Action(data).run()`. They should return a `...Action(data)`. That sends the instructions to run `action.run()` in the Ulauncher application runtime. But given this, it's better if our API doesn't expose the `run()` method to extensions, or makes it work (which would require sending the action to the extension server and running it there).

I'm going to close this though and make a new issue for that.
