### ISSUE TITLE
Alt+Space cannot be used as launch shortcut on Cinnamon

### ISSUE THREAD

**Issue by jmholla** [Ulauncher/Ulauncher#705]
I'm actually not certain that this is Cinnamon specific, but I know it's happening on Linux Mint.

### Steps to reproduce
1. Install Ulauncher
2. Set the shortcut to Alt+Enter (You'll have to manually click into the text box)
3. Try and use it.

### Current behavior
It opens the right-click-of-the-title-bar menu of the window you're on. If you're on the desktop, it does nothing.

### Expected behavior
Bring up Ulauncher. For reference, Synapse supports this key combination.

### Environment
**Ulauncher version**: 5.10.0
**Linux distro**: Mint
**Desktop environment**: Cinammon

### Logs

I don't have logs. I'm not exactly sure how I got it to capture the key combo in the first place. I think it was because Synapse was already capturing the combination. The hotkey window also doesn't capture all key combo events.

**Comment by troycurtisjr** [comment]
It may be that Ulauncher can't receive that key combination since it is already bound by the window manager which will get a first pass.  You can try following the instructions for Wayland on the wiki https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland which will setup the hot key in your window manager instead of trying to do it in Ulauncher.

**Comment by troycurtisjr** [comment]
Check out the referenced wiki article to see if it can help out. If not you can post back here and we can see how to help. I don't think ulauncher will be able to override these externally or already captured hotkeys.
