### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by RobOT05442309** [Ulauncher/Ulauncher#734]
Hello,

I wanted to know if there is any plan to add translation for this project (or if any already exist) ?

I'll be happy to do a full French translation for every settings and all other language related sentence, is there any file with all sentence that I could translate then send it back to you ?

Thanks for this nice launcher, keep up the good job !

**Comment by friday** [comment]
There are no such plans at the moment @RobOT05442309. Thank you for offering to help though.

One issue with supporting multiple languages is that this adds complexity to the source code, and if you want to change or add something then the programmers also have to know the languages supported or wait for others to contribute to those before making a release. At least if you don't want broken/mixed French/English as the result. For this reason it's not as easy as accepting a pull request.

**Comment by troycurtisjr** [comment]
Actually I think this is part of a broader idea of localization, since if we wanted to go down this path we'd need to come up with the overall approach and also tie it into the localization items that may be in place for the application files themselves. Linking to #393 and closing as a dup to keep all the context there.
