### ISSUE TITLE
Shortcut to existing application

### ISSUE THREAD

**Issue by loops** [Ulauncher/Ulauncher#749]
Hi, did my best to see if this feature already exists, apologies if I missed the way to do this.

Would like a shortcut or abbreviation for an existing application that is hard to search
by its application name.   One specific example is the "GNU Image Manipulation Program",
that can't be found by its common name "gimp".   Would like to be able to type "gimp" and
then launch the "GNU Image Manipulation Program".

I've made a shortcut named "gimp" that uses a script to launch the program, which is
okay.  But it would be nicer to not need a script and have the actual application with
the proper icon called up instead of a custom script.

### Describe the solution you'd like
Would be nice if there was another option for shortcuts which just pointed at an 
existing application to display and launch.

**Comment by friday** [comment]
You can copy the desktop entry from /usr/share/applications/gimp.desktop to ~/.local/share/applications and change the "Name[region code]=" part. If the file copy has the same name as the original it will override it. If you pick a different name you both versions will be searchable.

It already recognizes Gimp when you search for that though. Same if you enter "nautilus" or "baobab" you get Gnome Files and Disk Usage Analyzer because those are the real names of the executable.

**Comment by friday** [comment]
Closing this issue. This always worked, but now it works better than before:

![2021-08-21_21-45](https://user-images.githubusercontent.com/515120/130333261-8873bae2-00bf-4540-a63d-67432056dde3.png)
