### ISSUE TITLE
Document extension loading mechanism in extension dev guide

### ISSUE THREAD

**Issue by Jaakkonen** [Ulauncher/Ulauncher#818]
## Document extension loading mechanism in extension developer guide
Currently the extension developer documentation doesn't explain how `manifest.json` path is constructed from extension dir (`~/.local/share/ulauncher/extensions`) and path from `ULAUNCHER_WS_API`. Thus it's easy for developers to just try creating a extension somewhere except that path and then have their extension fail with `FileNotFoundError`.

### Solution
Add documentation (with links to code) explaining how the extension loading works. A plantuml sequence diagram might be helpful.

**Comment by Jaakkonen** [comment]
I'll maybe have time to contribute a PR for this in a week or two.

**Comment by friday** [comment]
@troycurtisjr is working on trying to change the extension communication method to not use websockets, so it may not be the best time for this.

**Comment by troycurtisjr** [comment]
This is true and while the high level sequence is pretty similar, there are
differences. For example there is a new "register" event that I coded to
come across from the extension to register the extension ID, whereas with
websockets the URL has the extension ID buried in it. In fact, perhaps
there is an opportunity here to improve things and have the register event
provide the path for ulauncher to use as the manifest.

All that to say, there are definitely some imminent changes to how some of
the particulars will function, but it sounds like useful documentation and
could provide a nice framework to tweak once I have my changes ready for
prime time. While I am running my personal ulauncher instance with my new
code, I still have more testing, a review of my approach, and updates to
the tests before I'd be looking to get it into dev, so I suspect it might
be a bit before it's ready. Probably weeks, not months.

**Comment by friday** [comment]
Assiged @troycurtisjr since this PR has been merged now (into the v6 branch), and the first thing to do is  update https://github.com/Ulauncher/Ulauncher/blob/v6/docs/extensions/debugging.rst (http://docs.ulauncher.io/en/latest/extensions/debugging.html) no reflect that :)

We should probably have a discussion about improving the extension debugging experience overall after that. A simple command to install a local directory as an extension, or run it directly without installing it would go a long way around. For example `ulauncher ext debug [path to directory]` `ulauncher ext install [path to directory]`.

`~/.local/share/` is not hard coded. It's loaded from the environment variable `XDG_DATA_HOME`, which when unset defaults to `~/.local/share/` or something. So there's no simple path to put extensions in that's true for everyone.

**Comment by friday** [comment]
Update: I figured out removing `ULAUNCHER_WS_API` was the right thing to do and added `EXTENSION_PREFERENCES` consistently to the warning produced by `--no-extensions`, as well as the documentation page. So the `--no-extensions` warning and the debugging.rst file should now be complete and correct as a reference for what the `ulauncher --debug-extension=/path/to/extension` flag would need to run.

The thing you have to run now is even uglier (my bad, because of #1047).

Example:
```sh
2022-06-14 14:19:31,156 ⚠️  WARNING Copy and run the following command to start com.github.hillaryychan.ulauncher-fzf ExtensionRunner.run:86
2022-06-14 14:19:31,156 ⚠️  WARNING VERBOSE=1 PYTHONPATH=/home/albin/src/Ulauncher:/home/albin/src/Ulauncher EXTENSION_PREFERENCES='{"kw":"fzf","search_type":"0","allow_hidden":"0","result_limit":"15","base_dir":"~","ignore_file":""}' /usr/bin/python3 /home/albin/.local/share/ulauncher/extensions/com.github.hillaryychan.ulauncher-fzf/main.py ExtensionRunner.run:87
```

So, even more reason for us to wrap this with something friendlier.

And we this way we don't have to encourage extension devs to put their project (source code) in ~/.local/share/ulauncher/extensions/ as we do now in [the tutorial](http://docs.ulauncher.io/en/latest/extensions/tutorial.html#creating-a-project). That part was always a bad idea imo.

**Comment by friday** [comment]
I'm putting myself as the assignee instead because this issue needs clarification for someone else to start working on it.

**Comment by friday** [comment]
It's been a long journey to get here, but I think #1203 and in particular https://github.com/Ulauncher/Ulauncher/pull/1203/commits/c14e21b3ec7620b5a7721a66a8cf74550475a543 should cover it.

I completely removed the old way. I never liked or used it, and it was complicated both as a dev trying to use it and for maintaining Ulauncher and making it consistent (like supporting loading the manifest and changing the settings when there is no extension id).

Now the only way to run extensions is to install them. You can install any git repo, including local paths. If you install a local repo you can push to that repo and then press the update button in the Ulauncher preferences.

This could be improved further by supporting CLI commands to install and update extension (#1018, #1150). I imagibe it would be really nice if you could run something like `ulauncher-ext install .` from the extension dir and have it install/update the local path.
