### ISSUE TITLE
Cannot run elementary terminal using RunScriptAction

### ISSUE THREAD

**Issue by OmarShawky1** [Ulauncher/Ulauncher#867]
I cannot run an extension using `io.elementary.terminal` in [File Search extension](https://github.com/OmarShawky1/ulauncher-file-search). 

To be particular, running ulauncher from applications menu makes this specific extension not work, while if i ran `$ulauncher`, it works pretty fine as following:

Working Extension:
![Working Extension](https://user-images.githubusercontent.com/51538094/144208603-2792d736-48cf-4027-8b9c-7c9cf1a4c44e.png)

Not Working Extension: (stucks here forever)
![Not Working Extension](https://user-images.githubusercontent.com/51538094/144208745-e2afbe32-0f6e-4c00-bff0-2f967c6e5991.png)

And it seems that the entire issue is within this code
```
    def get_open_in_terminal_script(self, path):
        """ Returns the script based on the type of terminal """
        terminal_emulator = self.preferences['terminal_emulator']

        # some terminals might work differently. This is already prepared for that.
        if terminal_emulator in [
                'gnome-terminal', 'terminator', 'tilix', 'xfce-terminal', 'io.elementary.terminal'
        ]:
            return RunScriptAction(terminal_emulator,
                                   ['--working-directory', path])

        return DoNothingAction()
```

**Comment by friday** [comment]
#767

**Comment by OmarShawky1** [comment]
1. brpaz stopped supporting this extension, that is why i am posting it here after i tried to resolve the issue by myself. 

2. Didn't find or understand what to do specifically from your code nor the documents found [here](https://docs.ulauncher.io/en/latest/extensions/actions.html#runscriptaction)

3. I did as what he said literally here: 
[image](https://user-images.githubusercontent.com/51538094/144212196-69b41ef0-d44e-416b-bed1-294d8ceb2091.png)

**Comment by friday** [comment]
I do agree that the documentation is lacking here. I don't quite know why that action is needed. I don't think it really helps extension developers. If you want to run a script or Launch an app with a specific parameter you can do it from Python with for example subprocess. No need to use Ulauncher's actions.

```py
import subprocess
subprocess.Popen(['terminator', '--working-directory', '/path/to/dir'])
```

There are lots of possible caveats with this, depending on how you use it. You can check how we are doing it in LaunchAppAction.py if you get issues with the terminal window closing if you kill the extension for example, but perhaps it's better for you just to get it working at all rather than perfectly.
