### ISSUE TITLE
allow customized or alternative jump (shortcut) keys instead of Alt+<number>

### ISSUE THREAD

**Issue by githorse** [Ulauncher/Ulauncher#964]
### Description

I'm a decent typist, but `Alt+<number>` is very slow for me and takes me out of my flow. Something like  `Ctrl+A`, for instance, would be much faster. 

What about a setting allowing users to switch to a `Ctrl+<letter>` scheme instead of `Alt+<number>`? Or, even better, allowing user-defined shortcut keys (defined exactly how, I'm not sure). 

Personally I'm a big fan of how browser Vim plugins ([Vimium](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/), etc.) handle links, where I type `f` and little badges show up on all the links with random letters that I can then type to jump to that link. Not sure that's really useful here as you have a flat list of items to click on, but maybe it's inspiration for something.)

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment]
I also would prefer Ctrl and no numbers. I don't know why it was created with Alt, so there might be a reason. If there is, then I'd rather keep it than adding an option for this. Too many options makes things complicated.

Ctrl+p and Ctrl+n are used for selecting the next/previous result (#796). That's not necessarily a problem. We could exclude those from the shortcuts, or let people define their own shortcuts (which would be easy as it's all stored as a [static string](https://github.com/Ulauncher/Ulauncher/commit/dfd476166b0d7c5e75ad59e516dfaf17350a812e) now) which would be easy to let users override. Then we could remove `p` and `n` by default, and let people add them back to override/bypass #796 (not sure it's a good idea, but it's technically possible). You could remove numbers, and change the letter order to QWERTY or whatever you like.

I would also prefer if the command didn't activate the item directly, but selects them like you do with the arrow keys or tab now (or ctrl+p/n). Then you get the visual confirmation before it does something, and you can do more than just launch the main action. Currently some actions have alt actions that you trigger with alt-enter, and I would prefer to be able to add to that via #326 and #476, and also add a "delete" (or "backspace") action for where it applies.

@troycurtisjr @gornostal and @RedBearAK might have input on this too.

**Comment by RedBearAK** [comment]
@friday @githorse 

I, too, asked if it was possible to change the shortcut modifier to `Ctrl`, before I realized what a problem that creates. 

I'm all for having completely customizable shortcuts for any piece of software, but things like Ctrl+A/Z/X/C/V/W/Q are all system-wide shortcuts for text functions, so the fact that the defaults are all using `Alt` is actually, I think, a good thing, since it's trying to use not just the digits but the whole alphabet (or as long as the results list is allowed to get). 

Trying to use `Ctrl` as the basis will interfere with all of those functions, which was one reason for asking for the zero to be added to the numeric shortcuts. The nice thing about the number keys is they aren't typically used for system-wide shortcuts with either `Alt` or `Ctrl`. Maybe with `Alt+Shift` or `Ctrl+Shift`, but usually not with a single modifier key. 

I realized what a problem it is to use the `Ctrl` key as the base modifier when I needed to remap `Ctrl` to `Alt` due to the fact that I use a keyboard remapper that makes my keyboard work like a Mac (the `Alt` key becomes `Ctrl` and acts like a Mac `Cmd` key). 

I had remapped the letters a-z, only to realize I had blocked the ability while doing a Ulauncher query to select all text, undo/redo, cut, copy, or paste. I don't see how you can avoid this problem if you attempt to use `Ctrl` as the base, and only, modifier key. Because of the way Ulauncher wants to use all the letters. 

The digits being at the beginning of the results list, which in v6 thanks to @friday will be ten digits after "zero" is added, bypasses this issue at least for the first ten results list items. And for my remaps I excluded `Alt+A/C` and limited the letters to up to just "h". So I got all my text functions back, at the expense of not being able to use the shortcut for list item numbers 11 and 13. 

>I would also prefer if the command didn't activate the item directly, but selects them like you do with the arrow keys or tab now (or ctrl+p/n). Then you get the visual confirmation before it does something, and you can do more than just launch the main action. Currently some actions have alt actions that you trigger with alt-enter, and I would prefer to be able to add to that via #326 and #476, and also add a "delete" (or "backspace") action for where it applies.

I do use the alternate action of `Cmd+Enter` or `Cmd+Click` with macOS Spotlight a lot, which goes to where the file/folder or application is located rather than directly opening it. If something similar were available with Ulauncher that would be nice. 

A much safer alternative to just using `Ctrl` would be, at least `Ctrl+Shift+<letter>`. But, just having the "base" shortcut modifier key(s) and the enumeration string configurable would let everyone deal with this in their own way. 

>I'm a decent typist, but Alt+<number> is very slow for me and takes me out of my flow. Something like Ctrl+A, for instance, would be much faster.

Relevant personal anecdote: 

Once upon a time I had spent a few years being a poor touch typist, and couldn't seem to get any better/faster than about 25 wpm with a lot of mistakes. Then late one night I just wanted to type more quietly on a mechanical keyboard, and so I put a folded pillow case over the keyboard. It made the keyboard much quieter. But within a couple of hours, I was surprised to notice that it was already much easier for my fingers to automatically find many keys that usually gave me trouble, even the number keys. My brain was no longer taking shortcuts because I could literally no longer see the keys. The improvement happened shockingly fast, and I've benefited from it ever since. The end.

**Comment by friday** [comment]
> I'm all for having completely customizable shortcuts for any piece of software, but things like Ctrl+A/Z/X/C/V/W/Q are all system-wide shortcuts for text functions, so the fact that the defaults are all using `Alt` is actually, I think, a good thing, since it's trying to use not just the digits but the whole alphabet (or as long as the results list is allowed to get).

I didn't think about Ctrl+A/X/C/V. :+1:

The rest don't really apply to Ulauncher. None of these are really system-wide. They have to be implemented by the apps. We use GTK that implements the text based ones for us.

I think Ctrl is still possible, but that makes 6 positions we should not use, and possibly more that I didn't think of. There might be distro or DE specific ones I'm not aware of also, and of course user-defined ones.

If we use the same as the Ulauncher show/hide keybinding itself, that would close the app down. We're not really in control of that since it's an external library with a custom format to store the keybinding. We could write code to understand it and avoid that key, but if people use [this way](https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland) we can't.

With the proposed custom setting for the shortkeys users could always get around this so I suggest we add that either way, because users could have custom keybindings for alt too:

![2022-01-26_09-20](https://user-images.githubusercontent.com/515120/151127445-62807bed-33c2-4a9d-8e51-8f8e2fa9e88a.png)


![2022-01-26_09-16](https://user-images.githubusercontent.com/515120/151127237-97d524da-04c5-4031-bd88-db2e3f51f828.png)

**Comment by RedBearAK** [comment]
@friday 

Coming from many years of macOS I am very used to the equivalent of Cmd+Space (the same position as Alt+Space on a PC keyboard). That's always been the shortcut for Spotlight since probably around when Spotlight was introduced by Apple in 2005. I've never really understood why it hasn't become more standard for something as fundamental as a desktop app launcher/universal search tool like Ulauncher. But Linux apparently inherited the usage of the Super/Win key for "Windows Start Menu" kinds of things.

**Comment by friday** [comment]
It's in the v6 branch now (see commit above). Follow #869 if you want to be notified of v6 release plans.

![2022-02-01_11-43](https://user-images.githubusercontent.com/515120/151955294-ca7a6c9e-59ea-48d7-b486-5564e7a52a29.png)
![2022-02-01_11-44](https://user-images.githubusercontent.com/515120/151955305-246927d3-7071-4fdd-8084-4088197dc7ef.png)
![2022-02-01_11-45](https://user-images.githubusercontent.com/515120/151955317-07ed68ab-a336-4afe-9a5f-1c93fd9a95b2.png)
